version: '3.8'

services:
  postgres1:
    image: postgres:15
    container_name: pg_shard1
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: shard1
    ports:
      - "5432:5432"
    volumes:
      - pgdata1:/var/lib/postgresql/data

  postgres2:
    image: postgres:15
    container_name: pg_shard2
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: shard2
    ports:
      - "5433:5432" # порт хоста отличается
    volumes:
      - pgdata2:/var/lib/postgresql/data
  
  postgres3:
    image: postgres:15
    container_name: pg_shard3
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: shard3
    ports:
      - "5434:5432" # порт хоста отличается
    volumes:
      - pgdata3:/var/lib/postgresql/data

  postgres4:
    image: postgres:15
    container_name: pg_shard4
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: shard4
    ports:
      - "5435:5432" # порт хоста отличается
    volumes:
      - pgdata4:/var/lib/postgresql/data
  
  postgres5:
    image: postgres:15
    container_name: pg_shard5
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: shard5
    ports:
      - "5436:5432" # порт хоста отличается
    volumes:
      - pgdata5:/var/lib/postgresql/data

  postgres6:
    image: postgres:15
    container_name: pg_shard6
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: shard6
    ports:
      - "5437:5432" # порт хоста отличается
    volumes:
      - pgdata6:/var/lib/postgresql/data

volumes:
  pgdata1:
  pgdata2:
  pgdata3:
  pgdata4:
  pgdata5:
  pgdata6:
